version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ml_service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ml_service
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: