services:
  postgres:
    image: postgres:16
    container_name: ml_service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ml_service
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ml_service_api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  worker:
    build: .
    container_name: ml_service_worker
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    command: [ "python", "-m", "app.workers.prediction_worker" ]

volumes:
  postgres_data: